version: "3.9"

services:
  app:
    build: .
    container_name: rust_app
    depends_on:
      - db
    environment:
      # Default to local Postgres, can override with Supabase URL
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/postgres}
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    container_name: local_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
